library(jsonlite)
uav <- stream_in(file("2016-06-20-0000Z.json"))
uav_flat <- flatten(uav)
library(tibble)
uav_tbl <- as_data_frame(uav_flat)
library(magrittr)
library(dplyr)
uav_tbl %>% mutate(acList = as.character(acList)) %>% select(acList)
#uav_aclist <- uav_tbl %>% mutate(acList = as.character(acList)) %>% select(acList)
#uav_tbl2 <- flatten(uav_aclist)
#uav_tbl3 <- as_data_frame(uav_tbl2)
library(stringr)
#libraryuav_tbl %>% select(-starts_with("src"), - starts_with("feeds"), - starts_with("srcFeed"), - starts_with("showFlg"), - starts_with("showPic"), - starts_with("stm"), - starts_with("Call"), - starts_with("InHg"), - starts_with("ResetTrail"), - starts_with("TrkH"), - starts_with("Type"), - starts_with("showSil"), - starts_with("showSil"), - starts_with("showSil"), - starts_with("Mdl"), - starts_with("Man"), - starts_with("CNum"), - starts_with("OpIcao"), - starts_with("Sqk"), -starts_with("flgH"), - starts_with("flgW"), - starts_with("totalAc"), - starts_with("lastDv"), - starts_with("shtTrlSec"))

uav_final <- uav_tbl %>% filter(str_detect(acList, "id")) %>% unnest(acList) %>% select(Id, Lat, Long, Alt, PosTime)
library(xlsx)
write.xlsx(uav_final, "b:/uav_1.xlsx")
