library(jsonlite)
uav <- stream_in(file("2016-06-20-0245Z.json"))
uav_flat <- flatten(uav)
library(tibble)
uav_tbl <- as_data_frame(uav_flat)
library(magrittr)
library(dplyr)
uav_tbl %>% mutate(acList = as.character(acList)) %>% select(acList)
library(stringr)
library(tidyr)
uav_final <- uav_tbl %>% filter(str_detect(acList, "id")) %>% unnest(acList) %>% select(Id, Lat, Long, Alt, PosTime)
uav_final <- unite(uav_final, Lat_Long_Alt_Time_val, -1, sep = ",")
library(xlsx)
write.xlsx(uav_final, "b:/YanYan/uav_1.xlsx")
